# Generated by Django 2.1.2 on 2018-10-09 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Control', '0002_datapoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='datapoint',
            name='client',
            field=models.ForeignKey(default=11, on_delete=django.db.models.deletion.CASCADE, to='Control.Raspi'),
            preserve_default=False,
        ),
    ]
