# Generated by Django 2.1.2 on 2018-10-15 23:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('secretid', models.CharField(max_length=30, unique=True)),
                ('ip', models.GenericIPAddressField()),
                ('datamode', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Datapoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('point', models.DecimalField(decimal_places=2, max_digits=10)),
                ('datetime', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datamana.Client')),
            ],
        ),
        migrations.CreateModel(
            name='Datatype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=30, unique=True)),
                ('client', models.ManyToManyField(to='Datamana.Client')),
            ],
        ),
        migrations.AddField(
            model_name='datapoint',
            name='datatype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Datamana.Datatype'),
        ),
    ]
