# Generated by Django 2.1.2 on 2018-11-29 16:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datamana', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['datetime']},
        ),
    ]
