# Generated by Django 2.1.2 on 2018-11-29 16:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Datamana', '0003_auto_20181129_1806'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='datapoint',
            options={'ordering': ['datetime']},
        ),
    ]
